### PR TITLE
Added a key normalizer

### LINKED ISSUE #49: Invalid key Uncaught PHP Exception
Hi, I am getting what appears to be random Critical error messages from time to time on our live environment such as this (domain name replaced):

request.CRITICAL: Uncaught PHP Exception Cache\Adapter\Common\Exception\InvalidArgumentException: "Invalid key: "www.mydomain.co.uk__.https:..maps.google.co.uk.maps__GET__f=q". The key contains one or more characters reserved for future extension: {}()/\@:" at /var/www/releases/20160317121445/vendor/cache/adapter-common/src/AbstractCachePool.php line 241 {"exception":"[object] (Cache\\Adapter\\Common\\Exception\\InvalidArgumentException(code: 0): Invalid key: \"www.mydomain.co.uk__.https:..maps.google.co.uk.maps__GET__f=q\". The key contains one or more characters reserved for future extension: {}()/\\@: at /var/www/releases/20160317121445/vendor/cache/adapter-common/src/AbstractCachePool.php:241)"} []

and this:

request.CRITICAL: Uncaught PHP Exception Cache\Adapter\Common\Exception\InvalidArgumentException: "Invalid key: "www.mydomain.co.uk__.index.php__GET__q=user/register". The key contains one or more characters reserved for future extension: {}()/\@:" at /var/www/releases/20160317121445/vendor/cache/adapter-common/src/AbstractCachePool.php line 241 {"exception":"[object] (Cache\\Adapter\\Common\\Exception\\InvalidArgumentException(code: 0): Invalid key: \"www.mydomain.co.uk__.index.php__GET__q=user/register\". The key contains one or more characters reserved for future extension: {}()/\\@: at /var/www/releases/20160317121445/vendor/cache/adapter-common/src/AbstractCachePool.php:241)"} []

In the second case it looks like it is because of the forward slash, but I don't know about the first one. More interestingly I don't have an index.php so why is that in there? Is this a bug in the router cache?

Thanks

### PR DESCRIPTION
**Pull request by Nyholm**
Added class for normalize keys. This will fix https://github.com/php-cache/issues/issues/49

### CODE REVIEW

**Comment by cryptiklemur** [comment]
I'm not sure this is entirely the best idea.... If we go this route, it should be togglable, and disabled by default.

**Comment by Nyholm** [comment]
Hm, but we should do something to prevent invalid chars. See https://github.com/php-cache/issues/issues/49

Im open to suggestions.

**Comment by cryptiklemur** [comment]
The issue we run into, is changing people's keys on the fly, without telling them. Could lead to issues where people check for the keys, and not being able to find them.

I think, if we made this togglable, it'd be fine. So the user would specifically have to ask for cleaned keys

**Comment by Nyholm** [comment]
Okej. So it is the migration you are worried about? Not the solution?

I think migration is not going to be a problem. This PR is only removing invalid keys ([ref](https://github.com/php-cache/cache-bundle/pull/56/files#diff-5ba1c729365c5c3ae9c24ad774512edcR167)). This will only avoid an exception from being thrown. Nobody will get a stored key changed.

**Comment by PaddyLock** [comment]
Hi, I have recently updated my set of packages to include this fix:

```
"cache/doctrine-adapter": "0.5.",
"cache/psr-6-doctrine-bridge": "2.1.",
"cache/cache-bundle": "0.4.3",
"cache/adapter-bundle": "0.3.",
"cache/memcached-adapter": "0.3.",
"cache/taggable-cache": "0.4.*",
"cache/hierarchical-cache": "0.2.1",
"cache/adapter-common": "0.3.0"
```

However, I still get the following error when clearing my cache

`Invalid key: "[Helios\CoreBundle\Entity\User$CLASSMETADATA][1]". The key contains one or more characters reserved for future extension: {}()/\@:`

I have also tried with this set of packages:

```
"cache/psr-6-doctrine-bridge": "dev-master",
"cache/cache-bundle": "dev-master",
"cache/adapter-bundle": "dev-master",
"cache/memcached-adapter": "dev-master",
```

but I get this error:

`Warning: call_user_func_array() expects parameter 1 to be a valid callback, class 'Cache\Adapter\Memcached\MemcachedCachePool' does not have a method 'clearTags'`

My config looks like this:

```
cache:
  doctrine:
    enabled: true
    use_tagging: true
    metadata:
      service_id: 'cache.provider.default_memcached'
      entity_managers:   [ default ]       # the name of your entity_manager connection
      document_managers: [ default ]       # the name of your document_manager connection
    result:
      service_id: 'cache.provider.default_memcached'
      entity_managers:   [ default, read ] # you may specify multiple entity_managers
    query:
      service_id: 'cache.provider.default_memcached'
      entity_managers: [ default ]
  router:
    enabled: true
    service_id: cache.provider.default_memcached
    ttl: 86400
```

**Pull request merged**
